# Generated by Django 3.1.7 on 2021-03-28 17:34

from django.db import migrations, models
import django.db.models.deletion
import portfolio_tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_symbol', models.CharField(max_length=20, unique=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('shares', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker_symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('shares', models.PositiveIntegerField()),
                ('trade_type', models.CharField(max_length=5, validators=[portfolio_tracking.models.validateTradeType])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_trade', to='portfolio_tracking.portfolio')),
            ],
        ),
    ]
