# Generated by Django 3.1.7 on 2021-03-29 06:47

from django.db import migrations, models
import portfolio_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=99, validators=[portfolio_tracking.models.validatePrice]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99, validators=[portfolio_tracking.models.validatePrice]),
        ),
    ]
