# Generated by Django 3.1.7 on 2021-03-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tracking', '0002_auto_20210329_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='portfolio',
        ),
    ]
